# Generated by Django 5.1.7 on 2025-03-18 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("color", models.CharField(default="#3498db", max_length=20, verbose_name="color")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["name"],
                "unique_together": {("name", "owner")},
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in grams or ounces (depending on user preference)",
                        max_digits=10,
                        verbose_name="weight",
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("g", "Grams"), ("oz", "Ounces")],
                        default="g",
                        max_length=2,
                        verbose_name="weight unit",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="URL")),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="price"
                    ),
                ),
                (
                    "currency",
                    models.CharField(default="USD", max_length=3, verbose_name="currency"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="gear_images/", verbose_name="image"
                    ),
                ),
                ("is_consumable", models.BooleanField(default=False, verbose_name="is consumable")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="gear_items.category",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ["name"],
            },
        ),
    ]
