# Generated by Django 5.1.7 on 2025-03-18 12:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gear_items", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GearList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                ("is_public", models.BooleanField(default=False, verbose_name="public")),
                (
                    "share_code",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True, verbose_name="share code"
                    ),
                ),
                (
                    "total_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated total weight of all items",
                        max_digits=10,
                        null=True,
                        verbose_name="total weight",
                    ),
                ),
                (
                    "weight_unit",
                    models.CharField(
                        choices=[("g", "Grams"), ("oz", "Ounces")],
                        default="g",
                        max_length=2,
                        verbose_name="weight unit",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gear_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "gear list",
                "verbose_name_plural": "gear lists",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="quantity")),
                ("is_worn", models.BooleanField(default=False, verbose_name="worn")),
                ("is_packed", models.BooleanField(default=False, verbose_name="packed")),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="order")),
                (
                    "gear_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_items",
                        to="gear_lists.gearlist",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_lists",
                        to="gear_items.item",
                    ),
                ),
            ],
            options={
                "verbose_name": "list item",
                "verbose_name_plural": "list items",
                "ordering": ["order"],
                "unique_together": {("gear_list", "item")},
            },
        ),
    ]
